# Generated by Django 4.1.4 on 2022-12-22 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='category',
            new_name='category_subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_categoty',
            field=models.ManyToManyField(through='news.Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
